# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'alpine'
  config.vm.hostname = 'alpine.default'
  config.vm.network :private_network, ip: '192.168.33.11'
  config.vm.network 'forwarded_port', guest: 22, host: 10022
  config.vbguest.auto_update = false
end
