# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :web do |web|
    web.vm.box = "ubuntu14.04"
    web.vm.hostname = "ubuntu.web.default"
    web.vm.network :private_network, ip:"192.168.50.11"
  end

  config.vm.define :web do |db|
    db.vm.box = "ubuntu14.04"
    db.vm.hostname = "ubuntu.web.default"
    db.vm.network :private_network, ip:"192.168.50.12"
  end
end
